export enum ComicDataTypes {
    FETCH_SPECIFIC_COMIC_SUCCESS = "comic-data/FETCH_SPECIFIC_COMIC_SUCCESS",
    FETCH_SPECIFIC_COMIC_FAIL = "comic-data/FETCH_SPECIFIC_COMIC_FAIL",
    FETCH_LATEST_COMIC_SUCCESS = "comic-data/FETCH_LATEST_COMIC_SUCCESS",
    FETCH_LATEST_COMIC_FAIL = "comic-data/FETCH_LATEST_COMIC_FAIL",
}
