export enum ComicDataTypes {
    FETCH_NEXT_COMIC_SUCCESS = "comic-data/FETCH_NEXT_COMIC_SUCCESS",
    FETCH_NEXT_COMIC_FAIL = "comic-data/FETCH_NEXT_COMIC_FAIL",
    FETCH_PREV_COMIC_SUCCESS = "comic-data/FETCH_PREV_COMIC_SUCCESS",
    FETCH_PREV_COMIC_FAIL = "comic-data/FETCH_PREV_COMIC_FAIL",
    FETCH_LATEST_COMIC_SUCCESS = "comic-data/FETCH_LATEST_COMIC_SUCCESS",
    FETCH_LATEST_COMIC_FAIL = "comic-data/FETCH_LATEST_COMIC_FAIL",
}
